const FILM_THRESHOLD=5e-6
const FILM_MAX_THICKNESS=1e-4

const INCHES = 2.54e-2
const GRAVITY = 9.8
const SEPERATION_VAR = -1e10

const DEFAULT_CLOSED = true
const DEFAULT_BOIL_WAITING_TIME = 1.0
const DEFAULT_RN_BOIL = 3e-6
const DEFAULT_INERTIA_F = 1.3
const DEFAULT_D = 1e-3
const DEFAULT_TUBESHAPE = "square"
const DEFAULT_NU = 3.6
const DEFAULT_SLUGNUM = 30
const DEFAULT_DFILM_RELATIVE = 0.04
const DEFAULT_FILM_FRACTION = 0.3
const DEFAULT_G = [0.0,0.0]
const DEFAULT_ETAPLUS = 0.6
const DEFAULT_ETAMINUS = 0.0
const DEFAULT_NUCLEATENUM = 250
const DEFAULT_L_NEWBUBBLE = 6e-3
const DEFAULT_CHARGE_RATIO = 0.46
const DEFAULT_SIGMA_CHARGE = 0.1

