name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
          - 'nightly'
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - name: Set up multithreading
        run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV # Set to desired number of threads
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v6
        with:
          files: lcov.info

  docs:
    name: Documentation
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/lyx-readme'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - uses: julia-actions/cache@v2
      - name: Generate literate pages
        run: |
          julia --project=test/ -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate()'
          cd test
          GROUP=Documentation julia --project=. runtests.jl
      - name: Install dependencies
        run: |
          julia --project=docs/ -e '
            using Pkg;
            Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
